# Settings for "Read the Docs" build.
# See <https://docs.readthedocs.io/>.
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
