# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.4" COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="3.3" COVERAGE="false"
install:
  - source tests/travis_install.sh
  - pip install -r requirements.txt
before_script:
  - git config --global user.email "roskakori@users.sourceforge.net"
  - git config --global user.name "Thomas Aglassinger"
script:
  - python setup.py test
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache:
  - apt
